[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
AllocCheck = "9b6a8646-10ed-4001-bbdc-1d2f46dfbb1a"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
ChunkSplitters = "ae650224-84b6-46f8-82ea-d812ca08434e"
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
CpuId = "adafc99b-e345-5852-983c-f28acb93d879"
Cthulhu = "f68482b8-f384-11e8-15f7-abe071a5a75f"
DistributedArrays = "aaf54ef3-cdf8-58ed-94cc-d582ad619b94"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Hwloc = "0e44f5e4-bd66-52a0-8798-143a42290a1d"
Hwloc_jll = "e33a78d0-f292-5ffc-b300-72abe9b543c8"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LIKWID = "bf22376a-e803-4184-b2ed-56326e3bff83"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MKL = "33e6dc65-8f57-5167-99aa-e5a354878fb2"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
MethodAnalysis = "85b6ec6f-f7df-4429-9514-a64bcd9ee824"
NUMA = "292f1341-b53f-425a-80e5-3597ad0961bf"
NVTX = "5da4648a-3479-48b8-97b9-01cb529c0a1f"
OhMyThreads = "67456a42-1dca-4109-a031-0a68de7e3ad5"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
PProf = "e4faabce-9ead-11e9-39d9-4379958e3056"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
STREAMBenchmark = "05e9033e-e298-417a-adae-495536c11ad4"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StableTasks = "91464d47-22a1-43fe-8b7f-2d57ee82463f"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
ThreadPinning = "811555cd-349b-4f26-b7bc-1f208b848042"
ThreadsX = "ac1d9e8a-700a-412c-b207-f0111f4b6c0d"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[extras]
CUDA_Runtime_jll = "76a88914-d11a-5bdc-97e0-2f5a05c973a2"
